<?php

namespace Splicewire\Beam\Ux\Codec;

use RuntimeException;
use Splicewire\Beam\Ux\Format\BodyStyle;
use Splicewire\Beam\Ux\Format\UxFormat;

/**
 * The **CSS codec** for a `UxType::Theme` entry (S1 seed set default, registered alongside
 * {@see TsxBodyCodec}/{@see MdxBodyCodec}) — bidirectional writing for a theme, the same reason the
 * tsx codec has it for a page/component: an author shouldn't be limited to a DB-only value with no
 * git-diffable, human-readable trace.
 *
 * `decode()` (body → source, the disk-mirror direction `PlacedDiskMirror` calls on every save) writes a
 * plain `:root { --token: value; }` block — the SAME role a materialized `.tsx` page plays: a durable,
 * git-tracked RECORD of what's currently live, not the live render's actual input (that stays the DB —
 * `ThemeResolver::resolve()` reads the entry's stored body directly, never this file).
 *
 * It is NOT a patch into a host's own hand-authored theme CSS (Tailwind `@theme` block, etc.) — this
 * codec has no opinion on any file it didn't generate itself. Its token names are derived mechanically
 * from the body's field path (`site.background` → `--theme-site-background`), not any host-specific
 * brand-token name — a theme entry's live value is not necessarily identical to whatever seeded it (an
 * author can edit the entry without touching the host's CSS at all), so borrowing that name would
 * silently misrepresent it. This also keeps the codec entry-agnostic: no per-slug mapping table to keep
 * in sync as more theme entries (tenant overrides, etc.) get added.
 *
 * `encode()` (source → body, the inverse) parses its OWN `:root {}` block back into the flat token map,
 * then un-flattens each `--theme-…` name back to its dotted field path (the exact inverse of
 * `decode()`'s naming transform), so a decode→encode round-trip returns the same body it started from.
 * This is a plain, hand-written parser, not a full CSS AST — deliberately: unlike a host's OWN
 * hand-authored CSS (arbitrary, foreign, exactly the case `App\Support\BrandTokens` in the splicewire
 * host app needs a real parser for), THIS format is entirely self-controlled — every file this codec
 * ever reads was either written by `decode()` itself or is a light hand-edit of that exact shape. A
 * regex over a grammar you fully own is a different risk profile than one over arbitrary third-party
 * CSS; see `App\Support\BrandTokens`'s own docblock (splicewire host app) for the contrasting case.
 */
class CssBodyCodec implements BodyCodec
{
    private const PREFIX = 'theme-';

    public function format(): UxFormat
    {
        return UxFormat::Css;
    }

    public function extension(): string
    {
        return UxFormat::Css->extension();
    }

    public function encode(string $raw, ?BodyStyle $style = null): array
    {
        // $style is ignored — body_style is a tsx-codec-local flavor, meaningless for css.
        $body = [];
        foreach (self::parseDeclarations(self::isolateRootBlock($raw)) as $token => $value) {
            if (! str_starts_with($token, self::PREFIX)) {
                continue;
            }

            data_set($body, self::fieldFor($token), $value);
        }

        return $body;
    }

    public function decode(array $body): string
    {
        $lines = [];
        foreach (self::flatten($body) as $field => $value) {
            $lines[] = '    --'.self::tokenFor($field).": {$value};";
        }

        $block = implode("\n", $lines);

        return <<<CSS
            /* Generated by {$this->format()->value}-format entries' BodyCodec on every theme save — a
             * durable, git-tracked RECORD of what's currently live (the actual render reads the
             * DB-stored entry directly, via Splicewire\Beam\Ux\Theme\ThemeResolver, never this file).
             * Hand-edits here round-trip on the next decode→encode, but are overwritten by the next
             * live save regardless. */
            :root {
            {$block}
            }

            CSS;
    }

    /** `site.editAccent` → `theme-site-edit-accent`. */
    private static function tokenFor(string $field): string
    {
        $kebab = strtolower((string) preg_replace('/(?<!^)[A-Z]/', '-$0', str_replace('.', '-', $field)));

        return self::PREFIX.$kebab;
    }

    /** `theme-site-edit-accent` → `site.editAccent` — the exact inverse of {@see tokenFor()}. */
    private static function fieldFor(string $token): string
    {
        $kebab = substr($token, strlen(self::PREFIX));
        [$group, $rest] = explode('-', $kebab, 2);

        $camel = lcfirst(str_replace(' ', '', ucwords(str_replace('-', ' ', $rest))));

        return "{$group}.{$camel}";
    }

    /**
     * Every string leaf in `$body`, keyed by its dotted path (`site.background`, `canvas.editAccent`,
     * …) — non-string values (there are none in a theme body today, but degrade-not-fabricate) are
     * skipped rather than stringified.
     *
     * @param  array<string, mixed>  $body
     * @return array<string, string>
     */
    private static function flatten(array $body, string $prefix = ''): array
    {
        $out = [];
        foreach ($body as $key => $value) {
            $path = $prefix === '' ? (string) $key : "{$prefix}.{$key}";
            if (is_array($value)) {
                $out += self::flatten($value, $path);
            } elseif (is_string($value) && $value !== '') {
                $out[$path] = $value;
            }
        }

        return $out;
    }

    /** The FIRST `:root { … }` block's inner text, found by counting brace depth (quote- and
     * comment-aware) rather than a non-greedy regex — correct even if a hand-edited value someday
     * nests a brace. Returns `''` when there's no `:root` block at all (an empty/malformed file
     * degrades to an empty body via {@see parseDeclarations}, not a crash). */
    private static function isolateRootBlock(string $css): string
    {
        $at = strpos($css, ':root');
        if ($at === false) {
            return '';
        }

        $open = strpos($css, '{', $at);
        if ($open === false) {
            return '';
        }

        $depth = 0;
        $quote = null;
        $length = strlen($css);
        for ($i = $open; $i < $length; $i++) {
            $char = $css[$i];

            if ($quote !== null) {
                if ($char === '\\') {
                    $i++;
                } elseif ($char === $quote) {
                    $quote = null;
                }

                continue;
            }

            if ($char === '/' && ($css[$i + 1] ?? '') === '*') {
                $close = strpos($css, '*/', $i + 2);
                if ($close === false) {
                    throw new RuntimeException('An unterminated comment in a theme CSS body.');
                }
                $i = $close + 1;

                continue;
            }

            if ($char === '"' || $char === "'") {
                $quote = $char;
            } elseif ($char === '{') {
                $depth++;
            } elseif ($char === '}') {
                $depth--;
                if ($depth === 0) {
                    return substr($css, $open + 1, $i - $open - 1);
                }
            }
        }

        return '';
    }

    /** @return array<string, string> */
    private static function parseDeclarations(string $block): array
    {
        preg_match_all('/--([\w-]+)\s*:\s*(.*?);/s', $block, $matches, PREG_SET_ORDER);

        $tokens = [];
        foreach ($matches as $m) {
            $tokens[$m[1]] = trim((string) preg_replace('/\s+/', ' ', $m[2]));
        }

        return $tokens;
    }
}
